const express = require("express");
const app = express();
const path = require("path");
const routes = require("./routes"); // <-- routes folder
const mongodb = require("./db/database");
const dotenv = require("dotenv");
const bodyParser = require("body-parser");
const swaggerUi = require("swagger-ui-express");
const swaggerDocument = require("./swagger.json"); // generated by swagger-autogen

dotenv.config();
const PORT = process.env.PORT || 8080;

app.use(express.json());
app.use(express.static(path.join(__dirname, "frontend")));
app.use(bodyParser.json());
app.use((req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept, Z-Key",
  );
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET, POST, PUT, DELETE, OPTIONS",
  );
  next();
});

// 👇 Add this line to mount Swagger UI
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerDocument));

mongodb.initDb((err) => {
  if (err) {
    console.error(err);
    process.exit(1);
  }

  app.use("/", routes); // Use main routes

  app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
  });
});
